version: '3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - default

  app:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - app:/var/www/html
      - ./php-conf:/usr/local/etc/php/conf.d
    networks:
      - default

  webserver:
    depends_on:
      - app
    image: nginx:alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - app:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - default
      - proxy-tier

volumes:
  db:
  app:

networks:
  default:
  proxy-tier:
    external:
      name: nginx-proxy_default
