version: '3'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    volumes: 
      - db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - default

  app:
    depends_on: 
      - db
    image: wordpress:fpm-alpine
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - app:/var/www/html
      - ./php-conf:/usr/local/etc/php/conf.d
    networks:
      - default

  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - app:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy-tier

volumes:
  app:
  db:

networks:
  default:
  proxy-tier:
    external:
      name: nginx-proxy_default
